logging:
  level:
    org:
      springframework:
        security: DEBUG
        context:
          annotation: DEBUG
    com:
      okta:
        spring: DEBUG
        
---

application:
  client-origin-url: http://localhost:4040

server:
  error:
    whitelabel:
      enabled: false
  port: 6060

okta:
  oauth2:
    issuer: https://dev-7g6g7ug82m5ecl4i.us.auth0.com/
    audience: https://hello-world.example.com

...
